date: 23 de Abril de 2020
department: "Ingenier\xEDa en Sistemas de Informaci\xF3n"
faculty: "Facultad Regional Concepci\xF3n del Uruguay"
logo: assets/logo-utn.png
question_bases:
- /home/makina/PycharmProjects/RandomTestGenerator/DefinicionProblemas/Conjuntos.tex
- /home/makina/PycharmProjects/RandomTestGenerator/DefinicionProblemas/LP1.tex
- /home/makina/PycharmProjects/RandomTestGenerator/DefinicionProblemas/LPC.tex
- /home/makina/PycharmProjects/RandomTestGenerator/DefinicionProblemas/Relaciones.tex
questions_per_file:
- 4
- 4
- 6
- 4
student_number: 1
subject: "Matem\xE1tica Discreta"
topic: "Primer Parcial Pr\xE1ctico  COMPLETO"
university: "Universidad Tecnol\xF3gica Nacional"
