date: 23 de Abril de 2020
department: "Ingenier\xEDa en Sistemas de Informaci\xF3n"
faculty: "Facultad Regional Concepci\xF3n del Uruguay"
logo: assets/logo-utn.png
question_bases:
- DefinicionProblemas/problems-1stprinciples
- /home/makina/PycharmProjects/RandomTestGenerator/DefinicionProblemas/problems-1stprinciples.tex
questions_per_file:
- 2
- 4
student_number: 4
subject: "Matem\xE1tica Discreta"
topic: "Primer Parcial Te\xF3rico"
university: "Universidad Tecnol\xF3gica Nacional"
